//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFitnessBuddy
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodEntry
    {
        public System.Guid ID { get; set; }
        public System.Guid gFood { get; set; }
        public System.Guid gUser { get; set; }
        public string strTime { get; set; }
        public Nullable<double> nQty { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Users Users { get; set; }
    }
}
