//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFitnessBuddy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public System.Guid ID { get; set; }
        public Nullable<decimal> nCalories { get; set; }
        public Nullable<decimal> nFat { get; set; }
        public Nullable<decimal> nCarb { get; set; }
        public Nullable<decimal> nProtein { get; set; }
        public string strName { get; set; }
    }
}
